FROM cdrx/pyinstaller-windows:python3

RUN apt-get update -y
RUN pip install --upgrade PyQt5 
RUN pip install --upgrade sip
RUN mkdir /app
COPY run.sh /app

WORKDIR /src
RUN chmod uga+x /app/run.sh
CMD ["/app/run.sh"]
