class JumpTables(object):
    BVNI = [
            "SYNC",
            "Ford Fiesta",
            "Ford Focus",
            "Ford Fusion",
            "Ford C-Max",
            "Ford Taurus",
            "Ford Mustang",
            "Ford Ecosport",
            "Ford Escape",
            "Ford Edge",
            "Ford Flex",
            "Ford Explorer",
            "Foprd Expedition",
            "Ford Ranger",
            "Ford F150",
            "Ford F250",
            "Ford F350",
            "Ford F450",
            "Ford F550",
            "Ford Transit Connect",
            "Ford Transit",
            "Ford E150",
            "Ford E250",
            "Ford E650",
            "Ford E750",
            "Lincoln MKZ",
            "Lincoln MKX",
            "Lincoln MKC",
            "Lincoln MKS",
            "Lincoln MKT",
            "Lincoln Navigator",
            "Ford Ka",
            "Ford Transit Courier",
            "Ford B-Max",
            "Ford Grand C-Max",
            "Ford Mondeo",
            "Ford Kuga",
            "Ford S-Max",
            "Ford Galaxy",
            "Ford Figo",
            "Ford Escort",
            "Ford Falcon",
            "Ford Everest",
            "Ford Terrirory",
            "Ford Raptor",
    ]

    _WDC = []

    _SS = [ # case splashscreen, no lookup table present in program
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Lincoln Black",
            "Lincoln Presidential",
            "Mustang",
            "GT350",
            "Vignale",
            "GT350",
            "Unknown",
            "Ford Performance ST",
            "Ford Performance RS",
            "Ford Performance GT",
            "Continental",
            "Unknown",
            ]

    _VS = [
            "Undefined",
            "Sedan",
            "Coupe/Convertable",
            "Pickup Truck",
            "SUV/CUV",
            "VAN",
            "Hatchback"
            ]

    _DT = [
            "FWD",
            "RWD",
            "AWD",
            "4WD",
            "Dually 2WD",
            "Dually 4WD",
            "Reserved",
            "Reserved"
            ]
    _AP = [
            "No media",
            "CD/MP3",
            "CD Changer MP3",
            "DVD MP3",
            "CD Harddrive",
            "Reserved",
            "Reserved",
            "Reserved"
            ]

    __GpsPatchType = [
            "Harada",
            "Laird",
            "reserved",
            ]

    _C = [ # case climate
            "Enable Climate Control Repeater for Dual Climate Control",
            "Disable Climate Control Repeater",
            "Enable Climate Control Repeater for Single Climate Control",
            "Disable Climate Control Repeater",
            "E8"
            ]

    _PA = [ # case Parkin_assistance
            "No PDC/PSM/SAPP (Non or Configuration C5)",
            "Rear PDC (Configuration C1 or C3)",
            "Rear/Front PDC (Configuration C6 or C7)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (NA HMI)",
            "Rear/SAPP (NA HMI)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (EU HMI)",
            "Rear/SAPP (EU HMI)",
            "Rear/Front PDC with APA",
            "APA Lite",
            "APA Lite Plus (SAPP/POA - 10 Channel)",
            "Unknkown / Reserved"
            ]
    _BPT = [ # case bluetooth pairing timeout
            "?"
            ]

    _V = [ # case vehicle type
            "Non HEV, BEV, PHEV",
            "C344",
            "C346",
            "CD391",
            "CD533",
            ]

    _VDV = [ # case visual design variant
            "Ford Classic",
            "Ford Timeless",
            "Lincoln Timeless",
            "Lincoln Next",
            ]

    _KC = [ # case KEY combination
            "Volume Down + F1",
            "Volume Down + Home",
            "SWC Down Volume + Center Previous Track",
            "Volume Down + Right OK",
            ]

    BAPI = [ # Bluetooth audi profile index
            "Profile %d"
            ]
    _AFL = [ # Electronic horizon"
            "Electronic Horizon Off",
            "Electronic Horizon for Informational Use Only",
            "Electronic Horizon for Non Active + Curve/Slope",
            "Electronic Horizon for Active (less Curve/Slope)",
            "Electronic Horizon for Active (with Curve/Slope)",
            ]

class Fields(object):

    @classmethod
    def combine(cls, start, stop):
        data = []
        for i in range(start, stop):
            if not hasattr(cls, 'de%02X' % (i)):
                break;
            data = data + getattr(cls, 'de%02X' % (i))
        return data

    de00 = []

    de01 = []

    de02 = []

    de03 = []

    de04 = []

    de05 = []

    de06 = []

    de07 = [ # indexes do not match a paticular order but instead a internal system, index change with changes in the settings so ... it's a guess but somewhat accurate as they stay in the same order
        {     'name': 'LANE_CHANGE_INDICATOR',
            'index': 169,
            'byte': 0,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'VS_CAL_SVC_IF_MESSAGE_SET CAN Legacy/New status (might be incorrect bit/byte)',
            'index': 181,
            'byte': 0,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'CCS config',
            'index': 183,
            'byte': 2,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'VS_CAL_SVC_IF_B479_STRATEGY',
            'index': 184,
            'byte': 0,
            'bit': 3, # not sure!
            'size': 7,
            'items': 0,
        },
        {     'name': 'APACSI_SIGNAL_STRATEGY ',
            'index': 188,
            'byte': 7,
            'bit': 4, # not sure!
            'size': 3,
            'items': 0,
        },
        {     'name': 'VS_CAL_SVC_IF_ICONS',
            'index': 197,
            'byte': 3,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'VS_CAL_SVC_IF_HAS_PARKING_HOTKEY',
            'index': 203,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_HOLD',
            'index': 208,
            'byte': 4,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'REVERSE_BRAKING_ASSIST',
            'index': 209,
            'byte': 2,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
    ]

    de08 = [
        {     'name': 'TIRE_PRESSURE_UNIT Support',
            'index': 217,
            'byte': 9,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TIRE_MOBILITY_KIT Support note, bit is possibly wrong could be 0, or 4',
            'index': 218,
            'byte': 9,
            'bit': 0, # ?
            'size': 1,
            'items': 0,
        },
        {     'name': 'TPMS_DISPLAY_UNIT',
            'index': 219,
            'byte': 9,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRACTION_CONTROL',
            'index': 220,
            'byte': 7,
            'bit': 2,
            'size': 3,
            'items': 0,
        },
        {     'name': 'DO NOT DISTURB',
            'index': 221,
            'byte': 3,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'SEAT_ADJUSTMENT',
            'index': 222,
            'byte': 2,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'SILENT_MODE',
            'index': 223,
            'byte': 5,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AlarmSystem',
            'index': 224,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Remote Start',
            'index': 225,
            'byte': 4,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUX_HEATER',
            'index': 226,
            'byte': 2,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Park Heater',
            'index': 227,
            'byte': 3,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'GLOBAL_WINDOW_OPEN',
            'index': 228,
            'byte': 2,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'GLOBAL_WINDOW_CLOSE',
            'index': 229,
            'byte': 2,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'COURTESY_WIPER',
            'index': 230,
            'byte': 1,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'REAR_REVERSE_GEAR_WIPE',
            'index': 231,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Power LiftGate',
            'index': 232,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Auto High Beam',
            'index': 233,
            'byte': 0,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'DAYTIME_RUNNING_LIGHTS',
            'index': 234,
            'byte': 2,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ADAPTIVE_HEADLAMPS_SUPPORT',
            'index': 235,
            'byte': 0,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTOLAMP_DELAY',
            'index': 236,
            'byte': 0,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'WELCOME_LIGHTING_DETECT',
            'index': 237,
            'byte': 1,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'REMOTE_UNLOCK',
            'index': 238,
            'byte': 3,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_FOLD_MIRRORS',
            'index': 239,
            'byte': 3,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'REVERSE_TILT_MIRRORS',
            'index': 240,
            'byte': 3,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'POWER_RUNNING_BOARD',
            'index': 241,
            'byte': 8,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_ENGINE_OFF_WithOutOverRide',
            'index': 242,
            'byte': 0,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_ENGINE_OFF_WithOverRide',
            'index': 243,
            'byte': 0,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PARK_LOCK_CONTROL',
            'index': 244,
            'byte': 9,
            'bit': 6,
            'size': 3,
            'items': 0,
        },
        {     'name': 'REMOTE_START_DriverSeat',
            'index': 245,
            'byte': 4,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'REMOTE_START Steering Wheel',
            'index': 246,
            'byte': 4,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_LOCK',
            'index': 247,
            'byte': 1,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_UNLOCK',
            'index': 248,
            'byte': 1,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_RELOCK',
            'index': 249,
            'byte': 1,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUDIBLE_LOCKING_FEEDBACK',
            'index': 250,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'EXTERIOR_LIGHTS_FEEDBACK',
            'index': 251,
            'byte': 6,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ADAPTIVE_HEADLAMPS_SETUP_SUPPORT',
            'index': 252,
            'byte': 1,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ACC_MENU',
            'index': 253,
            'byte': 0,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ADAPTIVE_CRUISE_CONTROL',
            'index': 254,
            'byte': 7,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ADJUSTABLE_SPEED_LIMITER',
            'index': 255,
            'byte': 0,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'INTELLIGENT_SPEED_ASSISTANCE',
            'index': 256,
            'byte': 4,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PRE_COLLISION_ASSIST',
            'index': 257,
            'byte': 5,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TOW_HAUL',
            'index': 258,
            'byte': 8,
            'bit': 6,
            'size': 1,
            'items': 0,
        },

        {     'name': 'BLINDSPOT_DETECTION',
            'index': 259,
            'byte': 4,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRAILER_BLINDSPOT_DETECTION',
            'index': 260,
            'byte': 8,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'WRONG_WAY_ALERT',
            'index': 261,
            'byte': 8,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRACTION_CONTROL',
            'index': 262,
            'byte': 0,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_START_STOP',
            'index': 263,
            'byte': 9,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'HILL_DECENT_CONTROL',
            'index': 264,
            'byte': 8,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'DRIVER_ALERT',
            'index': 265,
            'byte': 1,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRAILER_SWAY',
            'index': 266,
            'byte': 5,
            'bit': 7,
            'size': 1,
            'items': 0,
        },

        {     'name': 'DISTANCE_INDICATION',
            'index': 267,
            'byte': 2,
            'bit': 5,
            'size': 3,
            'items': 0,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION',
            'index': 268,
            'byte': 9,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'LANE_KEEPING_SENSITIVITY',
            'index': 269,
            'byte': 7,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'LANE_ASSIST_HAPTIC_INTENSITY',
            'index': 270,
            'byte': 6,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'LANE_CHANGE_ASSIST',
            'index': 271,
            'byte': 7,
            'bit': 6,
            'size': 3,
            'items': 0,
        },
        {     'name': 'INTELLIGENT_CRUISE_CONTROL',
            'index': 272,
            'byte': 6,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PRE_COLLISION_ASSIST_ACTIVE_BRAKING',
            'index': 273,
            'byte': 6,
            'bit': 6,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PRE_COLLISION_ASSIST_EVASIVE_STEERING',
            'index': 274,
            'byte': 6,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION_TOLERANCE',
            'index': 275,
            'byte': 7,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION_OVERSPEED_CHIME',
            'index': 276,
            'byte': 8,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'LANE_KEEPING_AID',
            'index': 277,
            'byte': 10,
            'bit': 5,
            'size': 3,
            'items': 0,
        },
        {     'name': 'LANE_KEEPING_ALERT',
            'index': 278,
            'byte': 10,
            'bit': 3,
            'size': 3,
            'items': 0,
        },
        {     'name': 'BTT_LITE',
            'index': 279,
            'byte': 11,
            'bit': 3,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AIR_SUSPENSION',
            'index': 280,
            'byte': 11,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Auto High Beam Menu',
            'index': 281,
            'byte': 11,
            'bit': 6,
            'size': 3,
            'items': 0,
        },
        {     'name': 'GRADE_ASSIST',
            'index': 283,
            'byte': 10,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'ONE_TWO_STAGE_UNLOCK',
            'index': 284,
            'byte': 10,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_HEIGHT',
            'index': 285,
            'byte': 11,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
        {     'name': 'CARGO_LOADING',
            'index': 286,
            'byte': 11,
            'bit': 0,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PASSENGER_AIRBAG',
            'index': 287,
            'byte': 11,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'KEY_FREE',
            'index': 288,
            'byte': 10,
            'bit': 2,
            'size': 1,
            'items': 0,
        },
        {     'name': 'INTELLIGENT_ACCESS',
            'index': 289,
            'byte': 5,
            'bit': 5,
            'size': 1,
            'items': 0,
        },
        {     'name': 'PREDICTIVE_LIGHTING_SUPPORT',
            'index': 290,
            'byte': 10,
            'bit': 7,
            'size': 1,
            'items': 0,
        },
        {     'name': 'AUTO_START_STOP_SPEED_THRESHOLD',
            'index': 291,
            'byte': 11,
            'bit': 1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'VS_CAL_SVC_IF_SYNC_HELP',
            'index': 294,
            'byte': 19,
            'bit': 4,
            'size': 1,
            'items': 0,
        },
    ]

    unknown = [
        {     'name': 'Unknown item 133, has to be bigger than 5 items on list so 3 bits',
            'index': 133,
            'byte': 0,
            'bit': 0,
            'size': 7,
            'items': 0,
        },
        {     'name': 'Max Defrost',
            'index': 215,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'QuadZone availability',
            'index': 200,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Dual button',
            'index': 214,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Auto heated Seats available',
            'index': 295,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 0,
        },
        {     'name': 'Clymate type',
            'index': 138,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Automatic',
            '1': 'Manual'
        },
        {     'name': 'Auto air refresh',
            'index': 204,
            'byte': -1,
            'bit': -1,
            'size': 1, # could be more
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled' # >= 1 is enabled
        },
        {     'name': 'PM Sensor',
            'index': 205,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': '2.5',
            '1': '10'
        },
        {     'name': 'Vehicle camera hotkey',
            'index': 206,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Not available',
            '1': 'Available'
        },
    ]
