class JumpTables(object):
    BVNI = [ # correct as from 5U5T
            "SYNC",
            "Ford Fiesta",
            "Ford Focus",
            "Ford Fusion",
            "Ford C-Max",
            "Ford Taurus",
            "Ford Mustang",
            "Ford EcoSport",
            "Ford Escape",
            "Ford Edge",
            "Ford Flex",
            "Ford Explorer",
            "Ford Expedition",
            "Ford Ranger",
            "Ford F150",
            "Ford F250",
            "Ford F350",
            "Ford F450",
            "Ford F550",
            "Ford Transit Connect",
            "Ford Transit",
            "Ford E150",
            "Ford E350",
            "Ford F650",
            "Ford F750",
            "Lincoln MKZ",
            "Lincoln MKS",
            "Lincoln MKC",
            "Lincoln MKX",
            "Lincoln MKT",
            "Lincoln Navigator",
            "Ford Ka",
            "Ford Fiesta",
            "Ford Transit Courier",
            "Ford B-Max",
            "Ford Grand C-Max",
            "Ford Mondeo",
            "Ford Kuga",
            "Ford S-Max",
            "Ford Galaxy",
            "Ford Figo",
            "Ford Escort",
            "Ford Falcon",
            "Ford Everest",
            "Ford Territory",
            "Ford Raptor",
            "Lincoln Continental",
            "Ford GT",
            "Ford Endeavour",
            "Ford Fiesta ST",
            "Ford Focus ST",
            "Ford Focus RS",
            "Lincoln Aviator",
            "Lincoln Corsair",
            "Ford Bronco",
            "Lincoln Nautilus",
            "Ford Puma",
            "Lincoln Aviator Coupe",
            "Ford Tourneo Connect",
            "Ford Tourneo Custom",
            "Shelby GT350",
            "Shelby GT500",
            "Bronco Maverick",
    ]

    _WDC = []

    _SS = [ # case splashscreen, no lookup table present in program
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Lincoln Black",
            "Lincoln Presidential",
            "Mustang",
            "GT350",
            "Vignale",
            "GT350",
            "Unknown",
            "Ford Performance ST",
            "Ford Performance RS",
            "Ford Performance GT",
            "Continental",
            "Unknown",
            ]

    _VS = [
            "Undefined",
            "Sedan",
            "Coupe/Convertable",
            "Pickup Truck",
            "SUV/CUV",
            "VAN",
            "Hatchback"
            ]

    _DT = [
            "FWD",
            "RWD",
            "AWD",
            "4WD",
            "Dually 2WD",
            "Dually 4WD",
            "Reserved",
            "Reserved"
            ]
    _AP = [
            "No media",
            "CD/MP3",
            "CD Changer MP3",
            "DVD MP3",
            "CD Harddrive",
            "Reserved",
            "Reserved",
            "Reserved"
            ]

    __GpsPatchType = [
            "Harada",
            "Laird",
            "reserved",
            ]

    _C = [ # case climate
            "Enable Climate Control Repeater for Dual Climate Control",
            "Disable Climate Control Repeater",
            "Enable Climate Control Repeater for Single Climate Control",
            "Disable Climate Control Repeater",
            "E8"
            ]

    _PA = [ # case Parkin_assistance
            "No PDC/PSM/SAPP (Non or Configuration C5)",
            "Rear PDC (Configuration C1 or C3)",
            "Rear/Front PDC (Configuration C6 or C7)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (NA HMI)",
            "Rear/SAPP (NA HMI)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (EU HMI)",
            "Rear/SAPP (EU HMI)",
            "Rear/Front PDC with APA",
            "APA Lite",
            "APA Lite Plus (SAPP/POA - 10 Channel)",
            "Unknkown / Reserved"
            ]
    _BPT = [ # case bluetooth pairing timeout
            "?"
            ]

    _V = [ # case vehicle type
            "Non HEV, BEV, PHEV",
            "C344",
            "C346",
            "CD391",
            "CD533",
            ]

    _VDV = [ # case visual design variant
            "Ford Classic",
            "Ford Timeless",
            "Lincoln Timeless",
            "Lincoln Next",
            ]

    _KC = [ # case KEY combination
            "Volume Down + F1",
            "Volume Down + Home",
            "SWC Down Volume + Center Previous Track",
            "Volume Down + Right OK",
            ]

    BAPI = [ # Bluetooth audi profile index
            "Profile %d"
            ]
    _AFL = [ # Electronic horizon"
            "Electronic Horizon Off",
            "Electronic Horizon for Informational Use Only",
            "Electronic Horizon for Non Active + Curve/Slope",
            "Electronic Horizon for Active (less Curve/Slope)",
            "Electronic Horizon for Active (with Curve/Slope)",
            ]

    @classmethod
    def table(cls, name):
        name = name.replace("__", "_").replace("__", "_")
        if not hasattr(cls, name):
            return []
        return getattr(cls, name)

class Fields(object):

    @classmethod
    def combine(cls, start, stop):
        data = []
        for i in range(start, stop):
            if not hasattr(cls, 'de%02X' % (i)):
                break;
            data = data + getattr(cls, 'de%02X' % (i))
        return data

    @classmethod
    def block(cls, block):
        if not hasattr(cls, "de%02X" % (block-1)):
            print(block, getattr(cls, "de%02X" % (block-1)))
            return None
        return getattr(cls, "de%02X" % (block-1))

    de00 = [
        {
            'name': 'Smart DSP',
            'index': 1,
            'byte': 0,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing DSP Messages',
            '1': 'Log missing DSP Messages (When configured for Smart DSP and Lincoln then enable THX Deep Note)',
        },
        {
            'name': 'AAM',
            'index': 2,
            'byte': 0,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing AAM messages',
            '1': 'Log Missing AAM messages (Send speaker walkaround request to ACM)',
        },
        {
            'name': 'SDARS',
            'index': 3,
            'byte': 0,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing SDARS (ACM) message',
            '1': 'Log Missing SDARS (ACM) message',
        },
        {
            'name': 'RSEM',
            'index': 4,
            'byte': 0,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing RSEM messages',
            '1': 'Log Missing RSEM messages',
        },
        {
            'name': 'PDC HMI',
            'index': 5,
            'byte': 0,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Rear Camera',
            'index': 6,
            'byte': 0,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'RVC Not Present',
            '1': 'RVC Present',
            '2': 'Reserved',
            '3': 'Reserved',
        },
        {
            'name': 'Illumination',
            'index': 7,
            'byte': 0,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'FNA Strategy',
            '1': 'FoE Strategy',
        },
        {
            'name': 'Extended Play',
            'index': 8,
            'byte': 1,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off',
        },
        {
            'name': 'Extended Play Time',
            'index': 9,
            'byte': 1,
            'bit': 1,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': '20 minutes',
            '1': '30 minutes (FNA)',
            '2': '40 minutes',
            '3': '60 minutes (FoE)',
        },
        {
            'name': 'Clock Master',
            'index': 10,
            'byte': 1,
            'bit': 3,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'APIM (NA Market CGEA 1.2)',
            '1': 'BCM (C1MCA and CGEA 1.3)',
            '2': 'IPC',
            '3': 'Reserved',
        },
        {
            'name': '10 Minute Clock',
            'index': 11,
            'byte': 1,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled(ALWAYS Disabled)',
            '1': 'Enabled',
        },
        {
            'name': 'CAN Steering Wheel Control Switches',
            'index': 12,
            'byte': 1,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not Available (do not log missing messages - also HW SWC)',
            '1': 'CGEA SCCM (log missing messages against missed SWC)',
            '2': 'SWMT (ie cursors and OK button over CAN) - C1MCA and CGEA 1.3',
            '3': 'SWFC (ie has function buttons) - C1MCA',
        },
        {
            'name': 'Auxiliary Input',
            'index': 13,
            'byte': 2,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Audio Only',
            '1': 'Audio and Video(Auxillary Input Installed=Present for any effect)',
        },
        {
            'name': 'Climate Control',
            'index': 14,
            'byte': 2,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA - North American Strategy',
            '1': 'C1MCA - European Strategy',
        },
        {
            'name': 'Chime Strategy',
            'index': 15,
            'byte': 2,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'North American Strategy',
            '1': 'European Strategy',
        },
        {
            'name': 'Type of Volume Knob',
            'index': 16,
            'byte': 2,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Rotary',
            '1': 'Horizontal',
        },
        {
            'name': 'Fader in Sound Menu',
            'index': 17,
            'byte': 2,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Fader in Sound Menu',
            '1': 'Fader not in Sound Menu',
        },
        {
            'name': 'Android Auto Projection Mode Auxiliary Input',
            'index': 18,
            'byte': 2,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enable',
            '1': 'Disable',
        },
        {
            'name': 'Bass/Mid/Treble Settings',
            'index': 19,
            'byte': 2,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Universal for audio modes',
            '1': 'Unique for audio modes',
        },
        {
            'name': 'Ignition Type',
            'index': 20,
            'byte': 2,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Key Start',
            '1': 'Push Button Start',
        },
        {
            'name': 'Tuner Type',
            'index': 21,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Single Tuner',
            '1': 'Dual Tuner or Single Tuner + Data Tuner',
        },
        {
            'name': 'Vehicle Driver Location',
            'index': 22,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Left Hand Drive (When user selects Driver HMI button, send driver occupancy mode CAN signal)  ',
            '1': 'Right Hand Drive (When user selects Driver HMI button, send passenger occupancy mode CAN signal) ',
        },
        {
            'name': 'WOW Seat',
            'index': 23,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'TMC',
            'index': 24,
            'byte': 3,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Disable TMC menu)',
            '1': 'Available (Enable TMC menu)',
        },
        {
            'name': 'DAB',
            'index': 25,
            'byte': 3,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Climate Front Zones',
            'index': 26,
            'byte': 3,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Dual Zone',
            '1': 'Single Zone',
        },
        {
            'name': 'Steering Wheel Angle Sensor',
            'index': 27,
            'byte': 3,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Relative',
            '1': 'Absolute',
        },
        {
            'name': 'HD Radio',
            'index': 28,
            'byte': 3,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'I-CAN Diagnostics',
            'index': 29,
            'byte': 4,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Smart Auto (Climate)',
            'index': 30,
            'byte': 4,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'My Temp',
            'index': 31,
            'byte': 4,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available(EFP Hard Button Present)',
        },
        {
            'name': 'Radio Tuner Market',
            'index': 32,
            'byte': 4,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non RDS Market (NA)',
            '1': 'RDS Market (Europe, APA, SA)',
        },
        {
            'name': 'Rear Climate',
            'index': 33,
            'byte': 4,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Heated Steering Wheel',
            'index': 34,
            'byte': 4,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available(or Hard Button Control)',
            '1': 'Available',
        },
        {
            'name': 'Heated Seats HMI',
            'index': 35,
            'byte': 4,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'None(Hard buttons or No Heated or Cooled Only)',
            '1': 'Cooled Only',
            '2': 'Heated and Cooled',
            '3': 'Heated Only (3-LEVEL)',
        },
        {
            'name': 'Brand',
            'index': 36,
            'byte': 5,
            'bit': 0,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Ford',
            '1': 'Reserved',
            '2': 'Lincoln',
            '3': 'Configurable Splash Screen',
        },
        {
            'name': 'Hybrid (HEV)',
            'index': 37,
            'byte': 5,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not a Hybrid (HEV) Vehicle',
            '1': 'Hybrid (HEV)Vehicle',
        },
        {
            'name': 'Microphone 2',
            'index': 38,
            'byte': 5,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present (Disable Mic2 Functionality)',
            '1': 'Present (Enable Mic2 Functionality)',
        },
        {
            'name': 'USB2',
            'index': 39,
            'byte': 5,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present (USB2 HMI will be disabled)',
            '1': 'Present (USB2 HMI will be enabled)',
        },
        {
            'name': 'Navigation Application',
            'index': 40,
            'byte': 5,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Navigation Application Turned Off',
            '1': 'Navigation Application Turned On (Common HMI)',
            '2': 'Navigation Application Turned On (External HMI)',
            '3': 'Not Used',
        },
        {
            'name': 'REFP (Rear EFP with Rotary Volume Knob)',
            'index': 41,
            'byte': 5,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'SD Slot',
            'index': 42,
            'byte': 6,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'SD Slot present',
            '1': 'SD slot not present',
        },
        {
            'name': 'Display Speed Limit in HMI (Traffic Sign Recognition Installed)',
            'index': 43,
            'byte': 6,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Speed Limit in HMI',
            '1': 'Speed Limit no in HMI (Traffic Sign Recognition)',
        },
        {
            'name': 'Start/Stop Vehicle',
            'index': 44,
            'byte': 6,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non Start/Stop',
            '1': 'Start Stop',
        },
        {
            'name': 'Transmission Type',
            'index': 45,
            'byte': 6,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Automatic',
            '1': 'Manual',
        },
        {
            'name': 'ECALL Message Stratergy',
            'index': 46,
            'byte': 6,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'North American Strategy (0x340 message)-CGEA 1.2',
            '1': 'European Strategy (0x4A message)-CGEA 1,3 or C1MCA',
        },
        {
            'name': 'Non-Metric Units for NAV',
            'index': 47,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Miles/Feet',
            '1': 'Miles/Yards',
        },
        {
            'name': 'Ambient Lighting',
            'index': 48,
            'byte': 6,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Ambient Lighting menu button shall not be displayed)',
            '1': 'Available (Ambient Lighting menu button shall be displayed)',
        },
        {
            'name': 'Door Keypad Code',
            'index': 49,
            'byte': 6,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Door Keypad menu button shall not be displayed)',
            '1': 'Available (Door Keypad menu button shall be displayed)',
        },
        {
            'name': 'Fuel Type',
            'index': 50,
            'byte': 7,
            'bit': 0,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Gasoline',
            '1': 'Diesel',
            '2': 'CNG',
            '3': 'BEV',
        },
        {
            'name': 'HW SWC',
            'index': 51,
            'byte': 7,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'SWAC with volume, PTT...  (Variant C)',
            '2': 'SWAC with Mode, Seek, etc... (Variant A)',
            '3': 'Reserved',
        },
        {
            'name': 'Mode Man Icon (Climate)',
            'index': 52,
            'byte': 7,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Climate Control Type',
            'index': 53,
            'byte': 7,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Automatic',
            '1': 'Manual (or if Climate is controlled via hardbuttons)',
        },
        {
            'name': 'Surround Sound Available in Occupancy Mode',
            'index': 54,
            'byte': 7,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Available',
            '1': 'Not Available',
        },
        {
            'name': 'Nav Repeater Format',
            'index': 55,
            'byte': 7,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Motorola Format',
            '1': 'Intel Format',
        },
        {
            'name': 'PHEV',
            'index': 56,
            'byte': 8,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Recirc Icon (Climate)',
            'index': 57,
            'byte': 8,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Ford Works',
            'index': 58,
            'byte': 8,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Front Camera',
            'index': 59,
            'byte': 8,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'DM6 HMI',
            'index': 60,
            'byte': 8,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Number of Bladders (MSC or WOW Seat)',
            'index': 61,
            'byte': 8,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': '9 Bladders',
            '1': '3 Bladders',
            '2': '7 Bladders',
            '3': '11 Bladders',
        },
        {
            'name': 'External CD',
            'index': 62,
            'byte': 8,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not present',
            '1': 'Present',
        },
        {
            'name': 'CGEA Version',
            'index': 63,
            'byte': 9,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA Version 1.2(also set C1MCA)',
            '1': 'CGEA Version 1.3 (will implement new power moding strategy)',
        },
        {
            'name': 'Heated Windshield HMI',
            'index': 64,
            'byte': 9,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not present',
            '1': 'Present',
        },
        {
            'name': 'Rear Climate Type (Only applicable when Rear Climate Configured)',
            'index': 65,
            'byte': 9,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Rear Manual w/o Air Flow Mode',
            '1': 'Rear Manual w/ Air Flow Mode',
            '2': 'Automatic',
            '3': 'Reserved',
        },
        {
            'name': 'Travel Link',
            'index': 66,
            'byte': 9,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'Turn travel link on',
        },
        {
            'name': 'NAV Repeater Conformance',
            'index': 67,
            'byte': 9,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'Current',
            '2': 'HUD Support',
            '3': 'Reserved',
        },
        {
            'name': 'Multi-contoured Seats (Legacy)',
            'index': 68,
            'byte': 9,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
    ]


    de01 = [
        {
            'name': 'Backup start passcode LBI Support - location does not make sense!',
            'index': 69,
            'byte': 12,
            'bit': 0,
            'size': 1,
            'type': 'mask',
            'items': 2,
            '0': 'Not supported',
            '1': 'Supported',
        },
        {
            'name': 'First Letter of Country Code-ASCII',
            'index': 70,
            'byte': 0,
            'bit': 0,
            'size': 8,
            'type': 'ascii',
        },
        {
            'name': 'Second Letter of Country Code-ASCII',
            'index': 71,
            'byte': 1,
            'bit': 0,
            'size': 8,
            'type': 'ascii',
        },
        {
            'name': 'Splash Screen',
            'index': 72,
            'byte': 2,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__SS',
        },
        {
            'name': 'Vehicle Style',
            'index': 73,
            'byte': 3,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__VS',
        },
        {
            'name': 'SDLC',
            'index': 74,
            'byte': 4,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present (if Present I-CAN Diag will be turned off regardless of setting for I-CAN diagnostics)',
        },
        {
            'name': 'Vehicle settings - B-car Only',
            'index': 76,
            'byte': 4,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off',
        },
        {
            'name': 'RVC Split View',
            'index': 77,
            'byte': 4,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': '360 Camera View',
            'index': 78,
            'byte': 4,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'B299 Strategy',
            'index': 79,
            'byte': 4,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'DAFVC Split View',
            'index': 80,
            'byte': 4,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Hill Start Assist - B-car Only',
            'index': 81,
            'byte': 4,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'ESP setting - B-car Only',
            'index': 82,
            'byte': 4,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'ESP hard button timer - B-car Only',
            'index': 83,
            'byte': 5,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'FoE',
            '1': 'FNa',
        },
        {
            'name': 'Message Center HMI - B-car Only',
            'index': 84,
            'byte': 5,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'List Browser',
            'index': 85,
            'byte': 5,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Navigation and Media',
            '1': 'Navigation Only',
            '2': 'None',
            '3': 'Reserved',
        },
        {
            'name': 'Electronic horizon',
            'index': 86,
            'byte': 5,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Electronic horizon Off',
            '1': 'Electronic horizon EH',
        },
        {
            'name': 'V363 Strategy',
            'index': 87,
            'byte': 5,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Outside Air Temperature HMI',
            'index': 88,
            'byte': 5,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Flank Guard HMI',
            'index': 89,
            'byte': 5,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Charge Port Lock',
            'index': 90,
            'byte': 6,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'Park Brake Type',
            'index': 91,
            'byte': 6,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Mechanical Park Brake (use signal PrkBrkActv_B_Actl)',
            '1': 'Electronic Park Brake (use signal PrkBrkStatus)',
        },
        {
            'name': 'Electronic Stability Control (ST Vehicles)',
            'index': 92,
            'byte': 6,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Rain Sensor- B-car Only',
            'index': 93,
            'byte': 6,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Hazard Spot Warning',
            'index': 94,
            'byte': 6,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'MyKey Settings - B-car Only',
            'index': 95,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Trailer Backup Assist',
            'index': 96,
            'byte': 6,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Rear Defrost',
            'index': 97,
            'byte': 6,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off(Mirror Defrost Icon Displayed)',
        },
        {
            'name': 'Deep Sleep',
            'index': 98,
            'byte': 7,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Deep Sleep Off',
            '1': 'Deep Sleep On',
        },
        {
            'name': 'REVELi/B&O Sound System',
            'index': 99,
            'byte': 7,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'PDC Architecture',
            'index': 100,
            'byte': 7,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA 1.3 Architecture',
            '1': 'C1MCA Architecture',
        },
        {
            'name': 'TCU',
            'index': 101,
            'byte': 7,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'Multi Camera Strategy',
            'index': 102,
            'byte': 7,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Hard Button Camera Toggle',
            '1': 'Soft Button Camera Toggle',
        },
        {
            'name': 'Trailer Reverse Guidance',
            'index': 103,
            'byte': 7,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'CHMSL Camera',
            'index': 104,
            'byte': 7,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Aux Camera',
            'index': 105,
            'byte': 7,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Autostore (Mixed mode presets)',
            'index': 106,
            'byte': 8,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {
            'name': 'Electronic Horizon Type',
            'index': 107,
            'byte': 8,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'MPP + Stubs',
            '1': 'MPP + Stub Expansion',
        },
        {
            'name': 'ICP(EFP) Type',
            'index': 108,
            'byte': 8,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'EFP',
            '1': 'ICP',
        },
        {
            'name': 'ICP(EFP) Branding',
            'index': 109,
            'byte': 8,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-Branded',
            '1': 'Branded',
        },
        {
            'name': 'ICP(EFP) Network',
            'index': 110,
            'byte': 8,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CAN',
            '1': 'LIN',
        },
        {
            'name': 'ECALL',
            'index': 111,
            'byte': 8,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {
            'name': 'Online Traffic for SA and China',
            'index': 112,
            'byte': 8,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Brazil Frequency supported by radio',
            'index': 113,
            'byte': 8,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-Brazil or Brazil Frequency is not Supported by Radio',
            '1': 'Brazil Frequency Supported by Radio',
        },
        {
            'name': 'AM Longwave/DAB L-Band',
            'index': 114,
            'byte': 9,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled(or Non-European Radio)',
            '1': 'Disabled',
        },
        {
            'name': 'Enhanced Memory',
            'index': 115,
            'byte': 9,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'CGEA1.3+ Illumination Strategy',
            'index': 116,
            'byte': 9,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-CGEA 1.3+',
            '1': 'CGEA 1.3+',
        },
        {
            'name': 'Illumination Change Step/Gradual',
            'index': 117,
            'byte': 9,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Step Change',
            '1': 'Gradual Change',
        },
        {
            'name': 'CD Alert Popup',
            'index': 118,
            'byte': 9,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Cross-Trafic Alert',
            'index': 119,
            'byte': 9,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Number of Personalizations',
            'index': 120,
            'byte': 9,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': '2',
            '2': '3',
            '3': '4',
        },
        {
            'name': 'South American Frequency - overlaps with WACM possibly old setting no longer funcitoning!',
            'index': 121,
            'byte': 10,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-South America or South American Frequency is Not Supported by Radio',
            '1': 'South American Frequency Supported by Radio',
        },
        {
            'name': 'WACM',
            'index': 122,
            'byte': 10,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Hotspot capable modem',
            'index': 123,
            'byte': 10,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'RVC Split view with non-multi camera',
            'index': 124,
            'byte': 10,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Online Traffic',
            'index': 125,
            'byte': 10,
            'bit': 3,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available with App',
            '2': 'Available with Modem',
            '3': 'Unknown'
        },
        {
            'name': 'Calm screen',
            'index': 126,
            'byte': 10,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Enhanced DAB (images with radio stations)',
            'index': 127,
            'byte': 10,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'AA OE Channel Feature (AACF)',
            'index': 128,
            'byte': 10,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Available',
            '1': 'Not Available',
        },
        {
            'name': 'BT Pairing Timeout in seconds',
            'index': 99121,
            'byte': 11,
            'bit': 0,
            'size': 8,
            'type': 'mul',
            'table': '_BPT',
            'offset': 0,
            'multiplier': 1,
            'unit': 'seconds',
            'min': 0,
            'max': 255,
        },
    ]


    de02 = [
        {
            'name': 'GPS Mount Type',
            'index': 129,
            'byte': 0,
            'bit': 0,
            'size': 8,
            'items': 8 ,
            'type': 'mask',
            '0': 'Roof Mount',
            '1': 'IP Mount (No Heated windshield)',
            '2': 'IP Mount (Heated windshield)',
            '3': 'Windshield (non Heated)',
            '4': 'Windshield (Heated)',
            '5': 'Reserved',
            '6': 'Reserved',
            '7': 'Reserved',
        },
        {
            'name': 'Vehicle format',
            'index': 130,
            'byte': 1,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '___V',
        },
        {
            'name': 'Visual Design Variants',
            'index': 131,
            'byte': 2,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '_VDV',
        },
        {
            'name': 'Drive Type',
            'index': 132,
            'byte': 3,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__DT',
        },
        {
            'name': 'Key Combination',
            'index': 133,
            'byte': 4,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__KC',
        },
    ]


    de03 = [
        {
            'name': 'Day night palette delay (seconds)',
            'index': 136,
            'byte': 0,
            'bit': 0,
            'size': 4,
            'type': 'mul',
            'table': '__AP',
            'offset': 0,
            'multiplier': 1,
            'unit': 'seconds',
            'min': 0,
            'max': 255,
        },
        {
            'name': 'Audio Player',
            'index': 136,
            'byte': 0,
            'bit': 4,
            'size': 4,
            'type': 'table',
            'table': '__AP',
        },
        {
            'name': 'Bluetooth Audio Profile Index',
            'index': 137,
            'byte': 1,
            'bit': 0,
            'size': 16,
            'type': 'table',
            'table': 'BAPI',
        },
        {
            'name': 'Climate Domain (will also disable climate VR)',
            'index': 138,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON - Automatic',
            '1': 'OFF - Manual',
        },
        {
            'name': 'Fan Repeater',
            'index': 139,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON',
            '1': 'OFF',
        },
        {
            'name': 'Temperature Repeater',
            'index': 140,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON',
            '1': 'OFF',
        },
        {
            'name': 'Legacy Climate',
            'index': 141,
            'byte': 3,
            'bit': 3,
            'size': 5,
            'type': 'table',
            'table': '___C',
        },
        {
            'name': 'BT Vehicle Nameplate ID',
            'index': 142,
            'byte': 4,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': 'BVNI',
        },
        {
            'name': 'ADAS Feature Level',
            'index': 143,
            'byte': 5,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '_AFL',
        },
        {
            'name': 'Parking Assistance',
            'index': 144,
            'byte': 6,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__PA',
        },
    ]


    de04 = [
        {
            'name': 'Front Track',
            'index': 135,
            'byte': 0,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
        {
            'name': 'Rear Track',
            'index': 136,
            'byte': 2,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
        {
            'name': 'Wheel Base',
            'index': 137,
            'byte': 4,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
    ]


    de05 = [
        {
            'name': 'Internal Gyro',
            'index': 138,
            'byte': 0,
            'size': 1,
            'bit': 0,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
            'items': 2 ,
        },
        {
            'name': 'Gyro on Bus',
            'index': 139,
            'byte': 0,
            'size': 1,
            'bit': 1,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
            'items': 2 ,
        },
        {
            'name': 'Ambient light type',
            'index': 1139,
            'byte': 0,
            'size': 1,
            'bit': 2,
            'type': 'mask',
            '0': 'Pantone color scheme',
            '1': 'Single color scheme',
            'items': 2 ,
        },
        {
            'name': 'Reverse Gear',
            'index': 2139,
            'byte': 0,
            'size': 1,
            'bit': 3,
            'type': 'mask',
            '0': 'Legacy',
            '1': 'New',
            'items': 2 ,
        },
        {
            'name': 'Enhanced Memory Phone As a Key',
            'index': 3139,
            'byte': 0,
            'size': 1,
            'bit': 4,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
            'items': 2 ,
        },
        {
            'name': 'Trailer Backup Assist 2',
            'index': 5139,
            'byte': 0,
            'size': 2,
            'bit': 5,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available with PSCM',
            '2': 'Available with IPMB',
            '3': 'Reserved',
            'items': 4 ,
        },
        {
            'name': 'Illuminaction Gateway Strategy',
            'index': 4139,
            'byte': 0,
            'size': 1,
            'bit': 7,
            'type': 'mask',
            '0': 'CGEA 1.3',
            '1': 'C1MCA',
            'items': 2 ,
        },

    ]


    de06 = [
        {
            'name': 'Vehicle Weight',
            'index': 140,
            'byte': 0,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 25500.0,
            'offset': 0,
            'multiplier': 100.0,
            'unit': 'KG',
        },
        {
            'name': 'ECO Route Curve',
            'index': 141,
            'byte': 1,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 1.0,
            'max': 256.0,
            'offset': 1,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Powertrain Efficiency',
            'index': 142,
            'byte': 2,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Regenerative Braking Efficiency Highway',
            'index': 143,
            'byte': 3,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Regenerative Braking Efficiency City',
            'index': 144,
            'byte': 4,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer X',
            'index': 145,
            'byte': 5,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer Y',
            'index': 146,
            'byte': 7,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer Z',
            'index': 147,
            'byte': 9,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Wheel Ticks to Revolution Front:  ',
            'index': 148,
            'byte': 11,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 40.0,
            'max': 295.0,
            'offset': 40,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Wheel Ticks to Revolution Rear',
            'index': 149,
            'byte': 12,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 40.0,
            'max': 295.0,
            'offset': 40,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Tire Circumference',
            'index': 150,
            'byte': 13,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 100.0,
            'max': 355.0,
            'offset': 100,
            'multiplier': 1.0,
            'unit': 'cm',
        },
        {
            'name': 'Distance from IP to rear axle',
            'index': 151,
            'byte': 14,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 100.0,
            'max': 65635.0,
            'offset': 100,
            'multiplier': 1.0,
            'unit': 'cm',
        },
    ]

    de07 = [ # indexes do not match a paticular order but instead a internal system, index change with changes in the settings so ... it's a guess but somewhat accurate as they stay in the same order

        {     'name': 'Powerfold Mirrors',
            'index': 169,
            'byte': 0,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Lane change indicator',
            'index': 169,
            'byte': 0,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Deflation Detection System',
            'index': 169,
            'byte': 0,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Park Lock Control',
            'index': 169,
            'byte': 0,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Information Chimes',
            'index': 170,
            'byte': 0,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Warning Chimes',
            'index': 171,
            'byte': 0,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Active City Stop',
            'index': 172,
            'byte': 0,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Alarm on Exit',
            'index': 173,
            'byte': 0,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On',
        },
        {     'name': 'Moonlight mode',
            'index': 174,
            'byte': 1,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On'
        },
        {     'name': 'TPMS',
            'index': 175,
            'byte': 1,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On'
        },
        {     'name': '4.2" HMI Menu Controller',
            'index': 176,
            'byte': 1,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Rotary Tune knob with OK Button',
            '1': '5-Way controller',
        },
        {     'name': 'Eco mode',
            'index': 178,
            'byte': 1,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Off',
            '1': 'On'
        },
        {     'name': 'Mobile Navigation',
            'index': 179,
            'byte': 1,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {     'name': 'Message set',
            'index': 180,
            'byte': 1,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Legacy',
            '1': 'New',
        },
        {     'name': 'X40 Setting',
            'index': 182,
            'byte': 1,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Pre X40 SDARS',
            '1': 'X40 SDARS',
        },

        {     'name': 'Customer Connectivity Settings',
            'index': 183,
            'byte': 1,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {     'name': 'B479 Strategy',
            'index': 184,
            'byte': 2,
            'bit': 0,
            'type': 'mask', # not sure!
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'EHEAT ?',
            'index': 1841,
            'byte': 2,
            'bit': 1,
            'type': 'mask', # not sure!
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Quad Zone',
            'index': 1841,
            'byte': 2,
            'bit': 2,
            'type': 'mask', # not sure!
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto Air Refresh',
            'index': 1841,
            'byte': 2,
            'bit': 3,
            'type': 'mask', # not sure!
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'PM Sensor for Auto Air Refresh',
            'index': 205,
            'byte': 2,
            'bit': 4,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'PM 2.5',
            '1': 'PM 10'
        },
        {     'name': 'Digital Rear View Camera',
            'index': 205,
            'byte': 2,
            'bit': 5,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Analog',
            '1': 'Digital'
        },
        {     'name': 'Boundary Alert',
            'index': 205,
            'byte': 2,
            'bit': 6,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled'
        },
        {     'name': 'Reverse Brake Assist',
            'index': 205,
            'byte': 2,
            'bit': 7,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled'
        },

        {     'name': 'Front park Aid Adjustable Chimes',
            'index': 205,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled'
        },
        {     'name': 'Rear park Aid Adjustable Chimes',
            'index': 205,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'type': 'mask',
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled'
        },
        {     'name': 'Enhanced Multi contour seats mode',
            'index': 185,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {   'name': 'MCS Mode (Power Lumbar)',
            'index': 197,
            'byte': 3,
            'bit': 3,
            'size': 2,
            'items': 4,
            'type': 'mask',
            '0': 'Disabled',
            '1': '2 way power lumbar available',
            '2': '4 way power lumbar available',
            '3': 'Reserved',
        },

        {     'name': 'EV Type',
            'index': 999,
            'byte': 3,
            'bit': 5,
            'size': 1,
            'items': 2,
            'type': 'mask',
            '0': 'Legacy',
            '1': 'New'
        },
        {     'name': 'Powerflow Type',
            'index': 205,
            'byte': 3,
            'bit': 6,
            'size': 2,
            'items': 4,
            'type': 'mask',
            '0': 'None',
            '1': 'MHT',
            '2': 'PS',
            '3': 'ERAD 4WD',
        },
        {     'name': 'Sound Immersion',
            'index': 203,
            'byte': 4,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Parking Hotkey',
            'index': 203,
            'byte': 4,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Camera Hotkey',
            'index': 203,
            'byte': 4,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Driver Assist Hotkey',
            'index': 203,
            'byte': 4,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto Hold',
            'index': 203,
            'byte': 4,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Video on Demand',
            'index': 203,
            'byte': 4,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Dark Car Mode',
            'index': 203,
            'byte': 4,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Power (Climate overlay)',
            'index': 203,
            'byte': 4,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'HS4 Network (HS4N)',
            'index': 203,
            'byte': 5,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Dual (Climate overlay)',
            'index': 203,
            'byte': 5,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Max Defrost (Climate overlay)',
            'index': 203,
            'byte': 5,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Max A/C (Climate overlay)',
            'index': 203,
            'byte': 5,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Driver only MCS',
            'index': 203,
            'byte': 5,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Wheel count Message (CANid)',
            'index': 203,
            'byte': 5,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'New (27A)',
            '1': 'Legacy (91)',
        },
        {     'name': 'Local Hazard Information',
            'index': 203,
            'byte': 5,
            'bit': 6,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'IPC Support Only',
            '2': 'IPC + HUD Support',
            '3': 'reserved',
        },
        {     'name': 'Digital Camera Vehicle Setting',
            'index': 203,
            'byte': 6,
            'bit': 2,
            'type': 'mask',
            'size': 3,
            'items': 8,
            '0': 'Vehicle 1',
            '1': 'Vehicle 2',
            '2': 'Vehicle 3',
            '3': 'Vehicle 4',
            '4': 'Vehicle 5',
            '5': 'Vehicle 6',
            '6': 'Vehicle 7',
            '7': 'Vehicle 8',
        },
        {     'name': 'Steering Angle sensor',
            'index': 203,
            'byte': 6,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Pinion',
            '1': 'Wheel',
        },
        {     'name': 'Driver Restriction Images',
            'index': 203,
            'byte': 6,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Allowed',
            '1': 'Restricted',
        },
        {     'name': 'Backup Start Passcode',
            'index': 203,
            'byte': 7,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Gracenote',
            'index': 203,
            'byte': 7,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'APACSI Signal Strategy',
            'index': 203,
            'byte': 7,
            'bit': 2,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disdabled',
            '1': 'Mode 1 (ApaTrgtDist_D_Stat not supported)',
            '2': 'Mode 2 (ApaMsgTxt_D_Rq not supported)',
            '3': 'Mode 3 (Both not supported)',
        },
        {     'name': 'Illumination Power Transitions',
            'index': 203,
            'byte': 7,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'On',
            '1': 'Off',
        },
        {     'name': 'Cloud Based Routing',
            'index': 203,
            'byte': 7,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Cloud Based Routing Fuel',
            'index': 203,
            'byte': 7,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Cloud Based Routing Weather',
            'index': 203,
            'byte': 7,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },


        {     'name': 'Number of mixed mode presets',
            'index': 203,
            'byte': 8,
            'bit': 0,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': '6 Presets per page',
            '1': '9 Presets per page',
            '2': '5 Presets per page',
            '3': '10 Presets per page',
        },
        {     'name': 'LIN 11-X',
            'index': 203,
            'byte': 8,
            'bit': 4,
            'type': 'mul',
            'size': 4,
            'offset': 0,
            'multiplier': 1,
            'unit': 'unitless',
            'min': 0,
            'max': 15,

        },
        {     'name': 'LIN 12-Y',
            'index': 203,
            'byte': 9,
            'bit': 0,
            'type': 'mul',
            'size': 4,
            'offset': 0,
            'multiplier': 1,
            'unit': 'unitless',
            'min': 0,
            'max': 15,

        },
        {     'name': 'LIN 13-Z',
            'index': 203,
            'byte': 9,
            'bit': 4,
            'type': 'mul',
            'size': 4,
            'offset': 0,
            'multiplier': 1,
            'unit': 'unitless',
            'min': 0,
            'max': 15,

        },
    ]

    de08 = [
        {     'name': 'AUTO_ENGINE_OFF_WithOutOverRide',
            'index': 242,
            'byte': 0,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'AUTO_ENGINE_OFF_WithOverRide',
            'index': 243,
            'byte': 0,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'ACC Menu',
            'index': 253,
            'byte': 0,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Adaptive Headlamps Control',
            'index': 235,
            'byte': 0,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Adjustable Speed Limiter Device',
            'index': 255,
            'byte': 0,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'AdvanceTrac control function',
            'index': 262,
            'byte': 0,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto High Beam Contrl',
            'index': 233,
            'byte': 0,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Autolamp Delay',
            'index': 236,
            'byte': 0,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {   'name': 'Auto Lock',
            'index': 247,
            'byte': 1,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Adaptive Headlamps Setup Support',
            'index': 252,
            'byte': 1,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto Relock',
            'index': 249,
            'byte': 1,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto Unlock (control function)',
            'index': 248,
            'byte': 1,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'City Safety',
            'index': 248,
            'byte': 1,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Welcome lighting detect (aka Approach Detection control function)',
            'index': 237,
            'byte': 1,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Courtecy wipe after wash',
            'index': 230,
            'byte': 1,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Driver alert system',
            'index': 265,
            'byte': 1,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },

        {     'name': 'Easy Entry/Exit (aka SEAT_ADJUSTMENT)',
            'index': 222,
            'byte': 2,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Forward Collision Warning (aka DISTANCE_INDICATION)',
            'index': 267,
            'byte': 2,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'None',
            '1': 'FCA',
            '2': 'FCA + FDA',
            '3': 'Reserved',
        },
        {     'name': 'Fuel Operated Heater',
            'index': 226,
            'byte': 2,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Global Window Open',
            'index': 228,
            'byte': 2,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Global Window Close',
            'index': 229,
            'byte': 2,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Daytime Running Lights Control Function',
            'index': 234,
            'byte': 2,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Temporary Mobility Kit', # check if not tire mobility kit
            'index': 234,
            'byte': 2,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Auto Fold Mirrors',
            'index': 239,
            'byte': 3,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Reverse tilt mirror function',
            'index': 240,
            'byte': 3,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Do not Disturb',
            'index': 221,
            'byte': 3,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Fuel Operated Park Heater',
            'index': 227,
            'byte': 3,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'One/Two stage unlocking (aka REMOTE_UNLOCK)',
            'index': 238,
            'byte': 3,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Perimiter Alarm with Reduced Guard Control Function',
            'index': 224,
            'byte': 3,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Power LiftGate Control Function',
            'index': 232,
            'byte': 3,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Rear Reverse Gear Wipe',
            'index': 231,
            'byte': 3,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start Climate Settings',
            'index': 245,
            'byte': 4,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start Driver Seat',
            'index': 245,
            'byte': 4,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start (Feature)',
            'index': 225,
            'byte': 4,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start Passenger Seat',
            'index': 245,
            'byte': 4,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start Rear Defrost',
            'index': 245,
            'byte': 4,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Remote Start Steering Wheel',
            'index': 246,
            'byte': 4,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Blindspot Detection (aka Side Detect)',
            'index': 259,
            'byte': 4,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Intelligent Speed Assistance',
            'index': 256,
            'byte': 4,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Trailer Sway',
            'index': 266,
            'byte': 5,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Front collission warning one menu (aka PRE_COLLISION_ASSIST)',
            'index': 257,
            'byte': 5,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Intelligent Access Menu',
            'index': 289,
            'byte': 5,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Silent Mode Control Function',
            'index': 223,
            'byte': 5,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Police Max Speed',
            'index': 999,
            'byte': 5,
            'bit': 4,
            'type': 'mask',
            'size': 4,
            'items': 16,
            '0': 'Off',
            '1': 'Reserved', '2': 'Reserved', '3': 'Reserved', '4': 'Reserved',
            '5': '90 mph',
            '6': '95 mph',
            '7': '100 mph',
            '8': '105 mph',
            '9': '110 mph',
            '10': '115 mph',
            '11': '120 mph',
            '12': '125 mph',
            '13': '130 mph',
            '14': '135 mph',
            '15': '140 mph',
        },
        {     'name': 'Police Enhanced Feature Speed',
            'index': 273,
            'byte': 6,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Pre collission braking assist Off/On',
            'index': 273,
            'byte': 6,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Audible Locking Feedback',
            'index': 250,
            'byte': 6,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Locking Visual Feedback (aka EXTERIOR_LIGHTS_FEEDBACK)',
            'index': 251,
            'byte': 6,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Evasice Steering Assist (Pre collission)',
            'index': 274,
            'byte': 6,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Lane Assist Heptic Intensity',
            'index': 270,
            'byte': 6,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Intelligent Adaptive Cruise Control',
            'index': 272,
            'byte': 6,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Adaptive Headlamps Feature',
            'index': 272,
            'byte': 6,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Lane Change Assist',
            'index': 271,
            'byte': 7,
            'bit': 0,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'Enabled',
            '2': 'Euro NCAP',
            '3': 'Reserved',
        },
        {     'name': 'Lane Keeping Sensitivity',
            'index': 269,
            'byte': 7,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Advanced Track hard button control',
            'index': 269,
            'byte': 7,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 4,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Tracktion control type',
            'index': 220,
            'byte': 7,
            'bit': 4,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'Tracktion Control',
            '2': 'IVD',
            '3': 'RSC',
        },
        {     'name': 'Adaptive Cruise Control',
            'index': 254,
            'byte': 7,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Traffic Sign NCAP Adaptions (aka TRAFFIC_SIGN_RECOGNITION_TOLERANCE)',
            'index': 275,
            'byte': 7,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {    'name': 'Traffic Sign Recognition Overspeed Chime',
            'index': 276,
            'byte': 8,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Tow Haul',
            'index': 258,
            'byte': 8,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Trailer Blind Spot Detection',
            'index': 260,
            'byte': 8,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Wrong Way Allert',
            'index': 261,
            'byte': 8,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Hill Descent Control',
            'index': 264,
            'byte': 8,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Rear brake assist',
            'index': 241,
            'byte': 8,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Power Running Board control function',
            'index': 241,
            'byte': 8,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Park Lock Control',
            'index': 244,
            'byte': 9,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Less Park Lock Control',
            '1': 'SUST Enable for Parking',
            '2': 'Temp Enable for Towing',
            '3': 'Enabled for Either Parking and Towing',
        },
        {     'name': 'Auto Start Stop',
            'index': 263,
            'byte': 9,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Perimiter Alarm Guard Reminder',
            'index': 263,
            'byte': 9,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Traffic Sign Recognition',
            'index': 268,
            'byte': 9,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Tire Pressure Unit Support by location',
            'index': 217, # 210
            'byte': 9,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'TPMS Dislay Unit',
            'index': 219,
            'byte': 9,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Centerstack Setting ?',
            'index': 218,
            'byte': 9,
            'bit': 7,
            'type': 'mask', # ?
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Predictive Lighting Support',
            'index': 290,
            'byte': 10,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Lane Keeping Aid',
            'index': 277,
            'byte': 10,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'Reduced, Enhanced',
            '2': 'Off, Reduced, Enhanced',
            '3': 'Off, On',
        },
        {     'name': 'Lane Keeping Alert',
            'index': 278,
            'byte': 10,
            'bit': 3,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'High, Normal, Low, Off',
            '2': 'On, Off',
            '3': 'High, Normal, Off',
        },
        {     'name': 'Key Free',
            'index': 288,
            'byte': 10,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Intelligent Assist',
            '1': 'Key Free',
        },
        {     'name': 'Grade Assist',
            'index': 283,
            'byte': 10,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'One/Two Stage Unlock',
            'index': 284,
            'byte': 10,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Passenger (One/Two State HMI)',
            '1': 'Commercial (Global Unlock HMI)',
        },
        {     'name': 'Auto High Beam Menu',
            'index': 281,
            'byte': 11,
            'bit': 0,
            'type': 'mask',
            'size': 2,
            'items': 4,
            '0': 'Disabled',
            '1': 'Auto High Beams',
            '2': 'Glare Free High Beams',
            '3': 'Adaptive Driving High Beams',
        },
        {     'name': 'Air Suspension SUMA Control Function',
            'index': 280,
            'byte': 11,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Air Suspension Auto Height SUMA',
            'index': 285,
            'byte': 11,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Blind Spot Trailer Tow Lite',
            'index': 279,
            'byte': 11,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Passenger Airbag Setting',
            'index': 287,
            'byte': 11,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'mHEV Start Stop Threshold Control Function',
            'index': 291,
            'byte': 11,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Air Suspension Cargo Loading SUMA',
            'index': 286,
            'byte': 11,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Climate Auto Seats',
            'index': 295,
            'byte': 19,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'VR For Radio Tuner (requires Gen4.1 Radio)',
            'index': 292,
            'byte': 19,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Driver Restriction Passenger Exception',
            'index': 294,
            'byte': 19,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {     'name': 'Sync Help',
            'index': 294,
            'byte': 19,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled',
        },
    ]

    unknown = [
        {     'name': 'Clymate type',
            'index': 138,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Automatic',
            '1': 'Manual'
        },
        {     'name': 'Some climate setting',
            'index': 178,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Not available',
            '1': 'Available'
        },
        {     'name': 'Mixed presets for MY20',
            'index': 215,
            'byte': -1,
            'bit': -1,
            'size': 2,
            'items': 4,
            '0': 'Not available',
            '1': 'Available'
        },
    ]
