class JumpTables(object):
    BVNI = [ # correct as from 5U5T
            "SYNC",
            "Ford Fiesta",
            "Ford Focus",
            "Ford Fusion",
            "Ford C-Max",
            "Ford Taurus",
            "Ford Mustang",
            "Ford EcoSport",
            "Ford Escape",
            "Ford Edge",
            "Ford Flex",
            "Ford Explorer",
            "Ford Expedition",
            "Ford Ranger",
            "Ford F150",
            "Ford F250",
            "Ford F350",
            "Ford F450",
            "Ford F550",
            "Ford Transit Connect",
            "Ford Transit",
            "Ford E150",
            "Ford E350",
            "Ford F650",
            "Ford F750",
            "Lincoln MKZ",
            "Lincoln MKS",
            "Lincoln MKC",
            "Lincoln MKX",
            "Lincoln MKT",
            "Lincoln Navigator",
            "Ford Ka",
            "Ford Fiesta",
            "Ford Transit Courier",
            "Ford B-Max",
            "Ford Grand C-Max",
            "Ford Mondeo",
            "Ford Kuga",
            "Ford S-Max",
            "Ford Galaxy",
            "Ford Figo",
            "Ford Escort",
            "Ford Falcon",
            "Ford Everest",
            "Ford Territory",
            "Ford Raptor",
            "Lincoln Continental",
            "Ford GT",
            "Ford Endeavour",
            "Ford Fiesta ST",
            "Ford Focus ST",
            "Ford Focus RS",
            "Lincoln Aviator",
            "Lincoln Corsair",
            "Ford Bronco",
            "Lincoln Nautilus",
            "Ford Puma",
            "Lincoln Aviator Coupe",
            "Ford Tourneo Connect",
            "Ford Tourneo Custom",
            "Shelby GT350",
            "Shelby GT500",
            "Bronco Maverick",
    ]

    _WDC = []

    _SS = [ # case splashscreen, no lookup table present in program
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Lincoln Black",
            "Lincoln Presidential",
            "Mustang",
            "GT350",
            "Vignale",
            "GT350",
            "Unknown",
            "Ford Performance ST",
            "Ford Performance RS",
            "Ford Performance GT",
            "Continental",
            "Unknown",
            ]

    _VS = [
            "Undefined",
            "Sedan",
            "Coupe/Convertable",
            "Pickup Truck",
            "SUV/CUV",
            "VAN",
            "Hatchback"
            ]

    _DT = [
            "FWD",
            "RWD",
            "AWD",
            "4WD",
            "Dually 2WD",
            "Dually 4WD",
            "Reserved",
            "Reserved"
            ]
    _AP = [
            "No media",
            "CD/MP3",
            "CD Changer MP3",
            "DVD MP3",
            "CD Harddrive",
            "Reserved",
            "Reserved",
            "Reserved"
            ]

    __GpsPatchType = [
            "Harada",
            "Laird",
            "reserved",
            ]

    _C = [ # case climate
            "Enable Climate Control Repeater for Dual Climate Control",
            "Disable Climate Control Repeater",
            "Enable Climate Control Repeater for Single Climate Control",
            "Disable Climate Control Repeater",
            "E8"
            ]

    _PA = [ # case Parkin_assistance
            "No PDC/PSM/SAPP (Non or Configuration C5)",
            "Rear PDC (Configuration C1 or C3)",
            "Rear/Front PDC (Configuration C6 or C7)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (NA HMI)",
            "Rear/SAPP (NA HMI)",
            "Rear/Front PDC/SAPP (Configuration C2 or C4) (EU HMI)",
            "Rear/SAPP (EU HMI)",
            "Rear/Front PDC with APA",
            "APA Lite",
            "APA Lite Plus (SAPP/POA - 10 Channel)",
            "Unknkown / Reserved"
            ]
    _BPT = [ # case bluetooth pairing timeout
            "?"
            ]

    _V = [ # case vehicle type
            "Non HEV, BEV, PHEV",
            "C344",
            "C346",
            "CD391",
            "CD533",
            ]

    _VDV = [ # case visual design variant
            "Ford Classic",
            "Ford Timeless",
            "Lincoln Timeless",
            "Lincoln Next",
            ]

    _KC = [ # case KEY combination
            "Volume Down + F1",
            "Volume Down + Home",
            "SWC Down Volume + Center Previous Track",
            "Volume Down + Right OK",
            ]

    BAPI = [ # Bluetooth audi profile index
            "Profile %d"
            ]
    _AFL = [ # Electronic horizon"
            "Electronic Horizon Off",
            "Electronic Horizon for Informational Use Only",
            "Electronic Horizon for Non Active + Curve/Slope",
            "Electronic Horizon for Active (less Curve/Slope)",
            "Electronic Horizon for Active (with Curve/Slope)",
            ]

    @classmethod
    def table(cls, name):
        name = name.replace("__", "_").replace("__", "_")
        if not hasattr(cls, name):
            return []
        return getattr(cls, name)

class Fields(object):

    @classmethod
    def combine(cls, start, stop):
        data = []
        for i in range(start, stop):
            if not hasattr(cls, 'de%02X' % (i)):
                break;
            data = data + getattr(cls, 'de%02X' % (i))
        return data

    @classmethod
    def block(cls, block):
        if not hasattr(cls, "de%02X" % (block-1)):
            print(block, getattr(cls, "de%02X" % (block-1)))
            return None
        return getattr(cls, "de%02X" % (block-1))

    de00 = [
        {
            'name': 'Smart DSP',
            'index': 1,
            'byte': 0,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing DSP Messages',
            '1': 'Log missing DSP Messages (When configured for Smart DSP and Lincoln then enable THX Deep Note)',
        },
        {
            'name': 'AAM',
            'index': 2,
            'byte': 0,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing AAM messages',
            '1': 'Log Missing AAM messages (Send speaker walkaround request to ACM)',
        },
        {
            'name': 'SDARS',
            'index': 3,
            'byte': 0,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing SDARS (ACM) message',
            '1': 'Log Missing SDARS (ACM) message',
        },
        {
            'name': 'RSEM',
            'index': 4,
            'byte': 0,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Do not log missing RSEM messages',
            '1': 'Log Missing RSEM messages',
        },
        {
            'name': 'PDC HMI',
            'index': 5,
            'byte': 0,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Rear Camera',
            'index': 6,
            'byte': 0,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'RVC Not Present',
            '1': 'RVC Present',
            '2': 'Reserved',
            '3': 'Reserved',
        },
        {
            'name': 'Illumination',
            'index': 7,
            'byte': 0,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'FNA Strategy',
            '1': 'FoE Strategy',
        },
        {
            'name': 'Extended Play',
            'index': 8,
            'byte': 1,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off',
        },
        {
            'name': 'Extended Play Time',
            'index': 9,
            'byte': 1,
            'bit': 1,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': '20 minutes',
            '1': '30 minutes (FNA)',
            '2': '40 minutes',
            '3': '60 minutes (FoE)',
        },
        {
            'name': 'Clock Master',
            'index': 10,
            'byte': 1,
            'bit': 3,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'APIM (NA Market CGEA 1.2)',
            '1': 'BCM (C1MCA and CGEA 1.3)',
            '2': 'IPC',
            '3': 'Reserved',
        },
        {
            'name': '10 Minute Clock',
            'index': 11,
            'byte': 1,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled(ALWAYS Disabled)',
            '1': 'Enabled',
        },
        {
            'name': 'CAN Steering Wheel Control Switches',
            'index': 12,
            'byte': 1,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not Available (do not log missing messages - also HW SWC)',
            '1': 'CGEA SCCM (log missing messages against missed SWC)',
            '2': 'SWMT (ie cursors and OK button over CAN) - C1MCA and CGEA 1.3',
            '3': 'SWFC (ie has function buttons) - C1MCA',
        },
        {
            'name': 'Auxiliary Input',
            'index': 13,
            'byte': 2,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Audio Only',
            '1': 'Audio and Video(Auxillary Input Installed=Present for any effect)',
        },
        {
            'name': 'Climate Control',
            'index': 14,
            'byte': 2,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA - North American Strategy',
            '1': 'C1MCA - European Strategy',
        },
        {
            'name': 'Chime Strategy',
            'index': 15,
            'byte': 2,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'North American Strategy',
            '1': 'European Strategy',
        },
        {
            'name': 'Type of Volume Knob',
            'index': 16,
            'byte': 2,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Rotary',
            '1': 'Horizontal',
        },
        {
            'name': 'Fader in Sound Menu',
            'index': 17,
            'byte': 2,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Fader in Sound Menu',
            '1': 'Fader not in Sound Menu',
        },
        {
            'name': 'Android Auto Projection Mode Auxiliary Input',
            'index': 18,
            'byte': 2,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enable',
            '1': 'Disable',
        },
        {
            'name': 'Bass/Mid/Treble Settings',
            'index': 19,
            'byte': 2,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Universal for audio modes',
            '1': 'Unique for audio modes',
        },
        {
            'name': 'Ignition Type',
            'index': 20,
            'byte': 2,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Key Start',
            '1': 'Push Button Start',
        },
        {
            'name': 'Tuner Type',
            'index': 21,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Single Tuner',
            '1': 'Dual Tuner or Single Tuner + Data Tuner',
        },
        {
            'name': 'Vehicle Driver Location',
            'index': 22,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Left Hand Drive (When user selects Driver HMI button, send driver occupancy mode CAN signal)  ',
            '1': 'Right Hand Drive (When user selects Driver HMI button, send passenger occupancy mode CAN signal) ',
        },
        {
            'name': 'WOW Seat',
            'index': 23,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'TMC',
            'index': 24,
            'byte': 3,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Disable TMC menu)',
            '1': 'Available (Enable TMC menu)',
        },
        {
            'name': 'DAB',
            'index': 25,
            'byte': 3,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Climate Front Zones',
            'index': 26,
            'byte': 3,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Dual Zone',
            '1': 'Single Zone',
        },
        {
            'name': 'Steering Wheel Angle Sensor',
            'index': 27,
            'byte': 3,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Relative',
            '1': 'Absolute',
        },
        {
            'name': 'HD Radio',
            'index': 28,
            'byte': 3,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'I-CAN Diagnostics',
            'index': 29,
            'byte': 4,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Smart Auto (Climate)',
            'index': 30,
            'byte': 4,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'My Temp',
            'index': 31,
            'byte': 4,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available(EFP Hard Button Present)',
        },
        {
            'name': 'Radio Tuner Market',
            'index': 32,
            'byte': 4,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non RDS Market (NA)',
            '1': 'RDS Market (Europe, APA, SA)',
        },
        {
            'name': 'Rear Climate',
            'index': 33,
            'byte': 4,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Heated Steering Wheel',
            'index': 34,
            'byte': 4,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available(or Hard Button Control)',
            '1': 'Available',
        },
        {
            'name': 'Heated Seats HMI',
            'index': 35,
            'byte': 4,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'None(Hard buttons or No Heated or Cooled Only)',
            '1': 'Cooled Only',
            '2': 'Heated and Cooled',
            '3': 'Heated Only (3-LEVEL)',
        },
        {
            'name': 'Brand',
            'index': 36,
            'byte': 5,
            'bit': 0,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Ford',
            '1': 'Reserved',
            '2': 'Lincoln',
            '3': 'Configurable Splash Screen',
        },
        {
            'name': 'Hybrid (HEV)',
            'index': 37,
            'byte': 5,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not a Hybrid (HEV) Vehicle',
            '1': 'Hybrid (HEV)Vehicle',
        },
        {
            'name': 'Microphone 2',
            'index': 38,
            'byte': 5,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present (Disable Mic2 Functionality)',
            '1': 'Present (Enable Mic2 Functionality)',
        },
        {
            'name': 'USB2',
            'index': 39,
            'byte': 5,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present (USB2 HMI will be disabled)',
            '1': 'Present (USB2 HMI will be enabled)',
        },
        {
            'name': 'Navigation Application',
            'index': 40,
            'byte': 5,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Navigation Application Turned Off',
            '1': 'Navigation Application Turned On (Common HMI)',
            '2': 'Navigation Application Turned On (External HMI)',
            '3': 'Not Used',
        },
        {
            'name': 'REFP (Rear EFP with Rotary Volume Knob)',
            'index': 41,
            'byte': 5,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'SD Slot',
            'index': 42,
            'byte': 6,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'SD Slot present',
            '1': 'SD slot not present',
        },
        {
            'name': 'Display Speed Limit in HMI (Traffic Sign Recognition Installed)',
            'index': 43,
            'byte': 6,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Speed Limit in HMI',
            '1': 'Speed Limit no in HMI (Traffic Sign Recognition)',
        },
        {
            'name': 'Start/Stop Vehicle',
            'index': 44,
            'byte': 6,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non Start/Stop',
            '1': 'Start Stop',
        },
        {
            'name': 'Transmission Type',
            'index': 45,
            'byte': 6,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Automatic',
            '1': 'Manual',
        },
        {
            'name': 'ECALL Message Stratergy',
            'index': 46,
            'byte': 6,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'North American Strategy (0x340 message)-CGEA 1.2',
            '1': 'European Strategy (0x4A message)-CGEA 1,3 or C1MCA',
        },
        {
            'name': 'Non-Metric Units for NAV',
            'index': 47,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Miles/Feet',
            '1': 'Miles/Yards',
        },
        {
            'name': 'Ambient Lighting',
            'index': 48,
            'byte': 6,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Ambient Lighting menu button shall not be displayed)',
            '1': 'Available (Ambient Lighting menu button shall be displayed)',
        },
        {
            'name': 'Door Keypad Code',
            'index': 49,
            'byte': 6,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available (Door Keypad menu button shall not be displayed)',
            '1': 'Available (Door Keypad menu button shall be displayed)',
        },
        {
            'name': 'Fuel Type',
            'index': 50,
            'byte': 7,
            'bit': 0,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Gasoline',
            '1': 'Diesel',
            '2': 'CNG',
            '3': 'BEV',
        },
        {
            'name': 'HW SWC',
            'index': 51,
            'byte': 7,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'SWAC with volume, PTT...  (Variant C)',
            '2': 'SWAC with Mode, Seek, etc... (Variant A)',
            '3': 'Reserved',
        },
        {
            'name': 'Mode Man Icon (Climate)',
            'index': 52,
            'byte': 7,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Climate Control Type',
            'index': 53,
            'byte': 7,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Automatic',
            '1': 'Manual (or if Climate is controlled via hardbuttons)',
        },
        {
            'name': 'Surround Sound Available in Occupancy Mode',
            'index': 54,
            'byte': 7,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Available',
            '1': 'Not Available',
        },
        {
            'name': 'Nav Repeater Format',
            'index': 55,
            'byte': 7,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Motorola Format',
            '1': 'Intel Format',
        },
        {
            'name': 'PHEV',
            'index': 56,
            'byte': 8,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Recirc Icon (Climate)',
            'index': 57,
            'byte': 8,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Ford Works',
            'index': 58,
            'byte': 8,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Front Camera',
            'index': 59,
            'byte': 8,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'DM6 HMI',
            'index': 60,
            'byte': 8,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Number of Bladders',
            'index': 61,
            'byte': 8,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': '9 Bladders',
            '1': '3 Bladders',
            '2': '7 Bladders',
            '3': '11 Bladders',
        },
        {
            'name': 'External CD',
            'index': 62,
            'byte': 8,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not present',
            '1': 'Present',
        },
        {
            'name': 'CGEA Version',
            'index': 63,
            'byte': 9,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA Version 1.2(also set C1MCA)',
            '1': 'CGEA Version 1.3 (will implement new power moding strategy)',
        },
        {
            'name': 'Heated Windshield HMI',
            'index': 64,
            'byte': 9,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not present',
            '1': 'Present',
        },
        {
            'name': 'Rear Climate Type (Only applicable when Rear Climate Configured)',
            'index': 65,
            'byte': 9,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Rear Manual w/o Air Flow Mode',
            '1': 'Rear Manual w/ Air Flow Mode',
            '2': 'Automatic',
            '3': 'Reserved',
        },
        {
            'name': 'Travel Link',
            'index': 66,
            'byte': 9,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'Turn travel link on',
        },
        {
            'name': 'NAV Repeater Conformance',
            'index': 67,
            'byte': 9,
            'bit': 5,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'Current',
            '2': 'HUD Support',
            '3': 'Reserved',
        },
        {
            'name': 'Multi-contoured Seats',
            'index': 68,
            'byte': 9,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
    ]


    de01 = [
        {
            'name': 'LBI Support - location does not make sense!',
            'index': 69,
            'byte': 12,
            'bit': 0,
            'size': 1,
            'type': 'mask',
            'items': 2,
            '0': 'Not supported',
            '1': 'Supported',
        },
        {
            'name': 'First Letter of Country Code-ASCII',
            'index': 70,
            'byte': 0,
            'bit': 0,
            'size': 8,
            'type': 'ascii',
        },
        {
            'name': 'Second Letter of Country Code-ASCII',
            'index': 71,
            'byte': 1,
            'bit': 0,
            'size': 8,
            'type': 'ascii',
        },
        {
            'name': 'Splash Screen',
            'index': 72,
            'byte': 2,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__SS',
        },
        {
            'name': 'Vehicle Style',
            'index': 73,
            'byte': 3,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__VS',
        },
        {
            'name': 'SDLC',
            'index': 74,
            'byte': 4,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present (if Present I-CAN Diag will be turned off regardless of setting for I-CAN diagnostics)',
        },
        {
            'name': 'Vehicle settings - B-car Only',
            'index': 76,
            'byte': 4,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off',
        },
        {
            'name': 'RVC Split View',
            'index': 77,
            'byte': 4,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': '360 Camera View',
            'index': 78,
            'byte': 4,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'B299 Strategy',
            'index': 79,
            'byte': 4,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'DAFVC Split View',
            'index': 80,
            'byte': 4,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Hill Start Assist - B-car Only',
            'index': 81,
            'byte': 4,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'ESP setting - B-car Only',
            'index': 82,
            'byte': 4,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'ESP hard button timer - B-car Only',
            'index': 83,
            'byte': 5,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'FoE',
            '1': 'FNa',
        },
        {
            'name': 'Message Center HMI - B-car Only',
            'index': 84,
            'byte': 5,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'List Browser',
            'index': 85,
            'byte': 5,
            'bit': 2,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Navigation and Media',
            '1': 'Navigation Only',
            '2': 'None',
            '3': 'Reserved',
        },
        {
            'name': 'Electronic horizon',
            'index': 86,
            'byte': 5,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Electronic horizon Off',
            '1': 'Electronic horizon EH',
        },
        {
            'name': 'V363 Strategy',
            'index': 87,
            'byte': 5,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Outside Air Temperature HMI',
            'index': 88,
            'byte': 5,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Flank Guard HMI',
            'index': 89,
            'byte': 5,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'Charge Port Lock',
            'index': 90,
            'byte': 6,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'Park Brake Type',
            'index': 91,
            'byte': 6,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Mechanical Park Brake (use signal PrkBrkActv_B_Actl)',
            '1': 'Electronic Park Brake (use signal PrkBrkStatus)',
        },
        {
            'name': 'Electronic Stability Control (ST Vehicles)',
            'index': 92,
            'byte': 6,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Rain Sensor- B-car Only',
            'index': 93,
            'byte': 6,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Hazard Spot Warning',
            'index': 94,
            'byte': 6,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'MyKey Settings - B-car Only',
            'index': 95,
            'byte': 6,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Trailer Backup Assist',
            'index': 96,
            'byte': 6,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Available',
            '1': 'Available',
        },
        {
            'name': 'Rear Defrost',
            'index': 97,
            'byte': 6,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'On',
            '1': 'Off(Mirror Defrost Icon Displayed)',
        },
        {
            'name': 'Deep Sleep',
            'index': 98,
            'byte': 7,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Deep Sleep Off',
            '1': 'Deep Sleep On',
        },
        {
            'name': 'REVEL Sound System',
            'index': 99,
            'byte': 7,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'PDC Architecture',
            'index': 100,
            'byte': 7,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CGEA 1.3 Architecture',
            '1': 'C1MCA Architecture',
        },
        {
            'name': 'TCU',
            'index': 101,
            'byte': 7,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
        },
        {
            'name': 'Multi Camera Strategy',
            'index': 102,
            'byte': 7,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Hard Button Camera Toggle',
            '1': 'Soft Button Camera Toggle',
        },
        {
            'name': 'Trailer Reverse Guidance',
            'index': 103,
            'byte': 7,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'CHMSL Camera',
            'index': 104,
            'byte': 7,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Aux Camera',
            'index': 105,
            'byte': 7,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Autostore',
            'index': 106,
            'byte': 8,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {
            'name': 'Electronic Horizon Type',
            'index': 107,
            'byte': 8,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'MPP + Stubs',
            '1': 'MPP + Stub Expansion',
        },
        {
            'name': 'ICP(EFP) Type',
            'index': 108,
            'byte': 8,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'EFP',
            '1': 'ICP',
        },
        {
            'name': 'ICP(EFP) Branding',
            'index': 109,
            'byte': 8,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-Branded',
            '1': 'Branded',
        },
        {
            'name': 'ICP(EFP) Network',
            'index': 110,
            'byte': 8,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'CAN',
            '1': 'LIN',
        },
        {
            'name': 'ECALL',
            'index': 111,
            'byte': 8,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled',
            '1': 'Disabled',
        },
        {
            'name': 'Online Traffic for SA and China',
            'index': 112,
            'byte': 8,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Brazil Frequency',
            'index': 113,
            'byte': 8,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-Brazil or Brazil Frequency is not Supported by Radio',
            '1': 'Brazil Frequency Supported by Radio',
        },
        {
            'name': 'AM Longwave/DAB L-Band',
            'index': 114,
            'byte': 9,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Enabled(or Non-European Radio)',
            '1': 'Disabled',
        },
        {
            'name': 'Enhanced Memory',
            'index': 115,
            'byte': 9,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'CGEA1.3+ Illumination Strategy',
            'index': 116,
            'byte': 9,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-CGEA 1.3+',
            '1': 'CGEA 1.3+',
        },
        {
            'name': 'Illumination Change Step/Gradual',
            'index': 117,
            'byte': 9,
            'bit': 3,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Step Change',
            '1': 'Gradual Change',
        },
        {
            'name': 'CD Alert Popup',
            'index': 118,
            'byte': 9,
            'bit': 4,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Cross-Trafic Alert',
            'index': 119,
            'byte': 9,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': 'Enabled',
        },
        {
            'name': 'Number of Personalizations',
            'index': 120,
            'byte': 9,
            'bit': 6,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Disabled',
            '1': '2',
            '2': '3',
            '3': '4',
        },
        {
            'name': 'South American Frequency - overlaps with WACM possibly old setting no longer funcitoning!',
            'index': 121,
            'byte': 10,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Non-South America or South American Frequency is Not Supported by Radio',
            '1': 'South American Frequency Supported by Radio',
        },
        {
            'name': 'WACM',
            'index': 122,
            'byte': 10,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Hotspot capable modem',
            'index': 123,
            'byte': 10,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'RVC Split view with non-multi camera',
            'index': 124,
            'byte': 10,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Online Traffic',
            'index': 125,
            'byte': 10,
            'bit': 3,
            'size': 2,
            'items': 4 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available with App',
            '2': 'Available with Modem',
            '3': 'Unknown'
        },
        {
            'name': 'Calm screen',
            'index': 126,
            'byte': 10,
            'bit': 5,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Not available',
            '1': 'Available',
        },
        {
            'name': 'Enhanced DAB (images with radio stations)',
            'index': 127,
            'byte': 10,
            'bit': 6,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Off',
            '1': 'On',
        },
        {
            'name': 'AA OE Channel Feature (AACF)',
            'index': 128,
            'byte': 10,
            'bit': 7,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'Available',
            '1': 'Not Available',
        },
        #{
        #    'name': 'BT Pairing Timeout',
        #    'index': 99121
        #    'byte': 10,
        #    'bit': 1,
        #    'size': 18,
        #    'type': 'table',
        #    'table': '_BPT',
        #},
    ]


    de02 = [
        {
            'name': 'GPS Mount Type',
            'index': 129,
            'byte': 0,
            'bit': 0,
            'size': 8,
            'items': 8 ,
            'type': 'mask',
            '0': 'Roof Mount',
            '1': 'IP Mount (No Heated windshield)',
            '2': 'IP Mount (Heated windshield)',
            '3': 'Windshield (non Heated)',
            '4': 'Windshield (Heated)',
            '5': 'Reserved',
            '6': 'Reserved',
            '7': 'Reserved',
        },
        {
            'name': 'Vehicle',
            'index': 130,
            'byte': 1,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '___V',
        },
        {
            'name': 'Visual Design Variants',
            'index': 131,
            'byte': 2,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '_VDV',
        },
        {
            'name': 'Drive Type',
            'index': 132,
            'byte': 3,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__DT',
        },
        {
            'name': 'Key Combination',
            'index': 133,
            'byte': 4,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__KC',
        },
    ]


    de03 = [
        {
            'name': 'Audio Player',
            'index': 136,
            'byte': 0,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__AP',
        },
        {
            'name': 'Bluetooth Audio Profile Index',
            'index': 137,
            'byte': 1,
            'bit': 0,
            'size': 16,
            'type': 'table',
            'table': 'BAPI',
        },
        {
            'name': 'Climate Domain (will also disable climate VR)',
            'index': 138,
            'byte': 3,
            'bit': 0,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON - Automatic',
            '1': 'OFF - Manual',
        },
        {
            'name': 'Fan Repeater',
            'index': 139,
            'byte': 3,
            'bit': 1,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON',
            '1': 'OFF',
        },
        {
            'name': 'Temperature Repeater',
            'index': 140,
            'byte': 3,
            'bit': 2,
            'size': 1,
            'items': 2 ,
            'type': 'mask',
            '0': 'ON',
            '1': 'OFF',
        },
        {
            'name': 'Climate',
            'index': 141,
            'byte': 3,
            'bit': 3,
            'size': 5,
            'type': 'table',
            'table': '___C',
        },
        {
            'name': 'BT Vehicle Nameplate ID',
            'index': 142,
            'byte': 4,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': 'BVNI',
        },
        {
            'name': 'ADAS Feature Level',
            'index': 143,
            'byte': 5,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '_AFL',
        },
        {
            'name': 'Parking Assistance',
            'index': 144,
            'byte': 6,
            'bit': 0,
            'size': 8,
            'type': 'table',
            'table': '__PA',
        },
    ]


    de04 = [
        {
            'name': 'Front Track',
            'index': 135,
            'byte': 0,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
        {
            'name': 'Rear Track',
            'index': 136,
            'byte': 2,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
        {
            'name': 'Wheel Base',
            'index': 137,
            'byte': 4,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 655.35,
            'offset': 0,
            'multiplier': 0.001,
            'unit': 'In',
        },
    ]


    de05 = [
        {
            'name': 'Internal Gyro',
            'index': 138,
            'byte': 0,
            'size': 1,
            'bit': 0,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
            'items': 2 ,
        },
        {
            'name': 'Gyro on Bus',
            'index': 139,
            'byte': 0,
            'size': 1,
            'bit': 1,
            'type': 'mask',
            '0': 'Not Present',
            '1': 'Present',
            'items': 2 ,
        },
    ]


    de06 = [
        {
            'name': 'Vehicle Weight',
            'index': 140,
            'byte': 0,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 25500.0,
            'offset': 0,
            'multiplier': 100.0,
            'unit': 'KG',
        },
        {
            'name': 'ECO Route Curve',
            'index': 141,
            'byte': 1,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 1.0,
            'max': 256.0,
            'offset': 1,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Powertrain Efficiency',
            'index': 142,
            'byte': 2,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Regenerative Braking Efficiency Highway',
            'index': 143,
            'byte': 3,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Regenerative Braking Efficiency City',
            'index': 144,
            'byte': 4,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 100.0,
            'offset': 0,
            'multiplier': 0.39215,
            'unit': '%',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer X',
            'index': 145,
            'byte': 5,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer Y',
            'index': 146,
            'byte': 7,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Install Angle of APIM for Accelerometer Z',
            'index': 147,
            'byte': 9,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 0.0,
            'max': 393.21,
            'offset': 0,
            'multiplier': 0.006,
            'unit': 'degrees',
        },
        {
            'name': 'Wheel Ticks to Revolution Front:  ',
            'index': 148,
            'byte': 11,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 40.0,
            'max': 295.0,
            'offset': 40,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Wheel Ticks to Revolution Rear',
            'index': 149,
            'byte': 12,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 40.0,
            'max': 295.0,
            'offset': 40,
            'multiplier': 1.0,
            'unit': 'unitless',
        },
        {
            'name': 'Tire Circumference',
            'index': 150,
            'byte': 13,
            'size': 8,
            'bit': 0,
            'type': 'mul',
            'min': 100.0,
            'max': 355.0,
            'offset': 100,
            'multiplier': 1.0,
            'unit': 'cm',
        },
        {
            'name': 'Distance from IP to rear axle',
            'index': 151,
            'byte': 14,
            'size': 16,
            'bit': 0,
            'type': 'mul',
            'min': 100.0,
            'max': 65635.0,
            'offset': 100,
            'multiplier': 1.0,
            'unit': 'cm',
        },
    ]

    de07 = [ # indexes do not match a paticular order but instead a internal system, index change with changes in the settings so ... it's a guess but somewhat accurate as they stay in the same order
        {     'name': 'LANE_CHANGE_INDICATOR',
            'index': 169,
            'byte': 0,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'VS_CAL_SVC_IF_MESSAGE_SET CAN Legacy/New status (might be incorrect bit/byte)',
            'index': 181,
            'byte': 0,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'CCS config',
            'index': 183,
            'byte': 2,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'VS_CAL_SVC_IF_B479_STRATEGY',
            'index': 184,
            'byte': 0,
            'bit': 4,
            'type': 'mask', # not sure!
            'size': 3,
            'items': 8,
        },
        {     'name': 'APACSI_SIGNAL_STRATEGY ',
            'index': 188,
            'byte': 7,
            'bit': 3,
            'type': 'mask', # not sure!
            'size': 2,
            'items': 4,
        },
        {     'name': 'VS_CAL_SVC_IF_ICONS',
            'index': 197,
            'byte': 3,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'VS_CAL_SVC_IF_HAS_PARKING_HOTKEY',
            'index': 203,
            'byte': 6,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_HOLD',
            'index': 208,
            'byte': 4,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'REVERSE_BRAKING_ASSIST',
            'index': 209,
            'byte': 2,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
    ]

    de08 = [
        {     'name': 'TIRE_PRESSURE_UNIT Support',
            'index': 217,
            'byte': 9,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TIRE_MOBILITY_KIT Support note, bit is possibly wrong could be 0, or 4',
            'index': 218,
            'byte': 9,
            'bit': 7,
            'type': 'mask', # ?
            'size': 1,
            'items': 2,
        },
        {     'name': 'TPMS_DISPLAY_UNIT',
            'index': 219,
            'byte': 9,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRACTION_CONTROL',
            'index': 220,
            'byte': 7,
            'bit': 5,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'DO NOT DISTURB',
            'index': 221,
            'byte': 3,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'SEAT_ADJUSTMENT',
            'index': 222,
            'byte': 2,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'SILENT_MODE',
            'index': 223,
            'byte': 5,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AlarmSystem',
            'index': 224,
            'byte': 3,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'Remote Start',
            'index': 225,
            'byte': 4,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUX_HEATER',
            'index': 226,
            'byte': 2,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'Park Heater',
            'index': 227,
            'byte': 3,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'GLOBAL_WINDOW_OPEN',
            'index': 228,
            'byte': 2,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'GLOBAL_WINDOW_CLOSE',
            'index': 229,
            'byte': 2,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'COURTESY_WIPER',
            'index': 230,
            'byte': 1,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'REAR_REVERSE_GEAR_WIPE',
            'index': 231,
            'byte': 3,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'Power LiftGate',
            'index': 232,
            'byte': 3,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'Auto High Beam',
            'index': 233,
            'byte': 0,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'DAYTIME_RUNNING_LIGHTS',
            'index': 234,
            'byte': 2,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ADAPTIVE_HEADLAMPS_SUPPORT',
            'index': 235,
            'byte': 0,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTOLAMP_DELAY',
            'index': 236,
            'byte': 0,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'WELCOME_LIGHTING_DETECT',
            'index': 237,
            'byte': 1,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'REMOTE_UNLOCK',
            'index': 238,
            'byte': 3,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_FOLD_MIRRORS',
            'index': 239,
            'byte': 3,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'REVERSE_TILT_MIRRORS',
            'index': 240,
            'byte': 3,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'POWER_RUNNING_BOARD',
            'index': 241,
            'byte': 8,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_ENGINE_OFF_WithOutOverRide',
            'index': 242,
            'byte': 0,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_ENGINE_OFF_WithOverRide',
            'index': 243,
            'byte': 0,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PARK_LOCK_CONTROL',
            'index': 244,
            'byte': 9,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'REMOTE_START_DriverSeat',
            'index': 245,
            'byte': 4,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'REMOTE_START Steering Wheel',
            'index': 246,
            'byte': 4,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_LOCK',
            'index': 247,
            'byte': 1,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_UNLOCK',
            'index': 248,
            'byte': 1,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_RELOCK',
            'index': 249,
            'byte': 1,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUDIBLE_LOCKING_FEEDBACK',
            'index': 250,
            'byte': 6,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'EXTERIOR_LIGHTS_FEEDBACK',
            'index': 251,
            'byte': 6,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ADAPTIVE_HEADLAMPS_SETUP_SUPPORT',
            'index': 252,
            'byte': 1,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ACC_MENU',
            'index': 253,
            'byte': 0,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ADAPTIVE_CRUISE_CONTROL',
            'index': 254,
            'byte': 7,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ADJUSTABLE_SPEED_LIMITER',
            'index': 255,
            'byte': 0,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'INTELLIGENT_SPEED_ASSISTANCE',
            'index': 256,
            'byte': 4,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PRE_COLLISION_ASSIST',
            'index': 257,
            'byte': 5,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TOW_HAUL',
            'index': 258,
            'byte': 8,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },

        {     'name': 'BLINDSPOT_DETECTION',
            'index': 259,
            'byte': 4,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRAILER_BLINDSPOT_DETECTION',
            'index': 260,
            'byte': 8,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'WRONG_WAY_ALERT',
            'index': 261,
            'byte': 8,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRACTION_CONTROL',
            'index': 262,
            'byte': 0,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_START_STOP',
            'index': 263,
            'byte': 9,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'HILL_DECENT_CONTROL',
            'index': 264,
            'byte': 8,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'DRIVER_ALERT',
            'index': 265,
            'byte': 1,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRAILER_SWAY',
            'index': 266,
            'byte': 5,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },

        {     'name': 'DISTANCE_INDICATION',
            'index': 267,
            'byte': 2,
            'bit': 2,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION',
            'index': 268,
            'byte': 9,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'LANE_KEEPING_SENSITIVITY',
            'index': 269,
            'byte': 7,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'LANE_ASSIST_HAPTIC_INTENSITY',
            'index': 270,
            'byte': 6,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'LANE_CHANGE_ASSIST',
            'index': 271,
            'byte': 7,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'INTELLIGENT_CRUISE_CONTROL',
            'index': 272,
            'byte': 6,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PRE_COLLISION_ASSIST_ACTIVE_BRAKING',
            'index': 273,
            'byte': 6,
            'bit': 1,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PRE_COLLISION_ASSIST_EVASIVE_STEERING',
            'index': 274,
            'byte': 6,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION_TOLERANCE',
            'index': 275,
            'byte': 7,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'TRAFFIC_SIGN_RECOGNITION_OVERSPEED_CHIME',
            'index': 276,
            'byte': 8,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'LANE_KEEPING_AID',
            'index': 277,
            'byte': 10,
            'bit': 2,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'LANE_KEEPING_ALERT',
            'index': 278,
            'byte': 10,
            'bit': 4,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'BTT_LITE',
            'index': 279,
            'byte': 11,
            'bit': 4,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AIR_SUSPENSION',
            'index': 280,
            'byte': 11,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'Auto High Beam Menu',
            'index': 281,
            'byte': 11,
            'bit': 1,
            'type': 'mask',
            'size': 2,
            'items': 4,
        },
        {     'name': 'GRADE_ASSIST',
            'index': 283,
            'byte': 10,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'ONE_TWO_STAGE_UNLOCK',
            'index': 284,
            'byte': 10,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_HEIGHT',
            'index': 285,
            'byte': 11,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'CARGO_LOADING',
            'index': 286,
            'byte': 11,
            'bit': 7,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PASSENGER_AIRBAG',
            'index': 287,
            'byte': 11,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'KEY_FREE',
            'index': 288,
            'byte': 10,
            'bit': 5,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'INTELLIGENT_ACCESS',
            'index': 289,
            'byte': 5,
            'bit': 2,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'PREDICTIVE_LIGHTING_SUPPORT',
            'index': 290,
            'byte': 10,
            'bit': 0,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'AUTO_START_STOP_SPEED_THRESHOLD',
            'index': 291,
            'byte': 11,
            'bit': 6,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
        {     'name': 'VS_CAL_SVC_IF_SYNC_HELP',
            'index': 294,
            'byte': 19,
            'bit': 3,
            'type': 'mask',
            'size': 1,
            'items': 2,
        },
    ]

    unknown = [
        {     'name': 'Unknown item 133, has to be bigger than 5 items on list so 3 bits',
            'index': 133,
            'byte': -1,
            'bit': -1,
            'size': 3,
            'items': 8,
        },
        {     'name': 'Multi contour seats mode',
            'index': 185,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Enhanve mcs available',
            '1': 'Driver only MCS',
        },
        {     'name': 'Multi contour seats mode',
            'index': 194,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'MCS mode settings -> see 198',
            '1': 'See -> 187',
        },
        {     'name': 'MCS Mode',
            'index': 197,
            'byte': -1,
            'bit': -1,
            'size': 2,
            'items': 4,
            '0': 'assume disabled',
            '1': '2 way power lumbar available',
            '2': '4 way power lumbar available',
            '3': 'assume disabled',
        },
        {     'name': 'Max Defrost',
            'index': 216,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
        },
        {     'name': 'QuadZone availability',
            'index': 201,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
        },
        {     'name': 'Dual button',
            'index': 215,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
        },
        {     'name': 'Auto heated Seats available',
            'index': 295,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
        },
        {     'name': 'Clymate type',
            'index': 138,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Automatic',
            '1': 'Manual'
        },
        {     'name': 'Auto air refresh',
            'index': 204,
            'byte': -1,
            'bit': -1,
            'size': 1, # could be more
            'items': 2,
            '0': 'Disabled',
            '1': 'Enabled' # >= 1 is enabled
        },
        {     'name': 'PM Sensor',
            'index': 205,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': '2.5',
            '1': '10'
        },
        {     'name': 'Vehicle camera hotkey',
            'index': 206,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Not available',
            '1': 'Available'
        },
        {     'name': 'Some climate setting',
            'index': 178,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Not available',
            '1': 'Available'
        },
        {     'name': 'Mixed presets for MY20',
            'index': 215,
            'byte': -1,
            'bit': -1,
            'size': 2,
            'items': 4,
            '0': 'Not available',
            '1': 'Available'
        },
        {     'name': 'Some enhanced DAB setting',
            'index': 292,
            'byte': -1,
            'bit': -1,
            'size': 1,
            'items': 2,
            '0': 'Not available',
            '1': 'Available'
        },

    ]
